version: '3.8'
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - main_db

  main_db:  
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33064:3306

   # Redis Server
  redis:
      image: redis:alpine3.16
      command: redis-server --appendonly yes --requirepass  "${REDIS_PASSWORD}"
      ports:
          - 63791:6379
